baseURL: "https://ru.algorithmica.org/"
theme:
- algorithmica
- reveal-hugo
pygmentsUseClasses: true
outputFormats:
  Reveal:
    baseName: index
    mediaType: text/html
    isHTML: true
defaultContentLanguage: en
languages:
  en:
    title: Algorithmica
    baseURL: https://en.algorithmica.org
    languageName: English
    languageCode: "en-us"
    weight: 1
  ru:
    title: Алгоритмика
    baseURL: https://ru.algorithmica.org
    languageName: Русский
    languageCode: "ru-ru"
    weight: 2
params:
  repo: "https://github.com/algorithmica-org/algorithmica"
  reveal_hugo:
    theme: white
    slide_number: true
    transition: none
    #custom_theme: "slides.sass"
    #custom_theme_compile: true
