backend:
  name: git-gateway
  branch: master
publish_mode: editorial_workflow
media_folder: "static/img"
public_folder: "/img"
collections:
- name: "page"
  label: "Page"
  folder: content
  create: true
  slug: "{{slug}}"
  fields:
  - label: "Title"
    name: "title"
    widget: "string"
  - label: Body
    name: body
    widget: 'code'
- name: "section"
  label: "Section"
  folder: "content"
  filter: {field: "contenttype", value: "section"}    
  create: true
  slug: "_index.{{language}}"
  fields:
  - {label: "Visible", name: "visible", widget: "boolean", default: false, required: false}
  - {label: "Content Type", name: "contenttype", widget: "hidden", default: "section"}
  - {label: "Language", name: "language", widget: "select", options: ["ca", "es", "en"]}
  - {label: "Order", name: "weight", widget: "number", default: 1}
  - {label: "Title", name: "title", widget: "string", tagname: "h1"}
  - {label: "Description", name: "description", widget: "text", required: false}
  meta:
  - {label: "Date", name: "date", widget: "datetime"}
  editor:
  - preview: false