backend:
  name: git-gateway
  branch: master
publish_mode: editorial_workflow
media_folder: "static/img"
public_folder: "/img"
collections:
- name: "content"
  label: "Content"
  folder: content
  create: true
slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
fields:
- {label: "Title", name: "title", widget: "string"}
- {label: "Publish Date", name: "date", widget: "datetime"}
