backend:
  name: git-gateway
  branch: master
publish_mode: editorial_workflow
media_folder: "static/img"
public_folder: "/img"
collections:
- name: "page"
  label: "Page"
  folder: content
  create: true
  slug: "{{slug}}"
  fields:
  - label: 'Code'
    name: 'code'
    widget: 'code'
