backend:
  name: git-gateway
  branch: master
publish_mode: editorial_workflow
media_folder: "static/img"
public_folder: "/img"
collections:
- name: "content"
  label: "Content"
  folder: "{{folder}}"
  filter: {field: "contenttype", value: "content"}    
  create: true
  slug: "{{urlkey}}.{{language}}"
  fields:
  - {label: "Draft", name: "draft", widget: "boolean", default: true, required: false}
  - {label: "Content Type", name: "contenttype", widget: "hidden", default: "content"}
  - {label: "Language", name: "language", widget: "select", options: ["ca", "es", "en"]}
  - {label: "Key (for translations linking)", name: "urlkey", widget: "string", required: true}
  - {label: "Sort", name: "weight", widget: "number", default: 1}
  - {label: "Title", name: "title", widget: "string", tagname: "h1"}
  - {label: "Description", name: "description", widget: "text", required: false}
  - {label: "Date", name: "date", widget: "datetime"}
  - {label: "Content", name: "body", widget: "markdown"}
  meta:
  - {label: "Date", name: "date", widget: "datetime"}
  editor:
  - preview: false
- name: "section"
  label: "Section"
  folder: "content"
  filter: {field: "contenttype", value: "section"}    
  create: true
  slug: "_index.{{language}}"
  fields:
  - {label: "Visible", name: "visible", widget: "boolean", default: false, required: false}
  - {label: "Content Type", name: "contenttype", widget: "hidden", default: "section"}
  - {label: "Language", name: "language", widget: "select", options: ["ca", "es", "en"]}
  - {label: "Order", name: "weight", widget: "number", default: 1}
  - {label: "Title", name: "title", widget: "string", tagname: "h1"}
  - {label: "Description", name: "description", widget: "text", required: false}
  meta:
  - {label: "Date", name: "date", widget: "datetime"}
  editor:
  - preview: false